name: Twitter Wallpaper Botu

on:
  schedule:
    # Türkiye Saati (UTC+3) Ayarlı 7 Vakit
    - cron: '0 5 * * *'   # 08:00
    - cron: '0 7 * * *'   # 10:00
    - cron: '30 9 * * *'  # 12:30
    - cron: '0 12 * * *'  # 15:00
    - cron: '30 14 * * *' # 17:30
    - cron: '0 17 * * *'  # 20:00
    - cron: '30 19 * * *' # 22:30
  workflow_dispatch:

jobs:
  calistir:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      # ANALİZDEKİ TAVSİYE: Python 3.10 kullanıyoruz.
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Botu Çalıştır
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          # 6 Tokeni de alıyoruz
          HF_TOKEN_1: ${{ secrets.HF_TOKEN_1 }}
          HF_TOKEN_2: ${{ secrets.HF_TOKEN_2 }}
          HF_TOKEN_3: ${{ secrets.HF_TOKEN_3 }}
          HF_TOKEN_4: ${{ secrets.HF_TOKEN_4 }}
          HF_TOKEN_5: ${{ secrets.HF_TOKEN_5 }}
          HF_TOKEN_6: ${{ secrets.HF_TOKEN_6 }}
        run: python bot.py
