- name: Install dependencies
  run: pip install pillow google-generativeai tweepy
name: Twitter Botu

on:
  schedule:
    # Türkiye Saati (UTC+3) Ayarları:
    # Günde 8 Kere Paylaşım
    # 07:00 TR -> 04:00 UTC
    # 10:00 TR -> 07:00 UTC
    # 12:00 TR -> 09:00 UTC
    # 15:00 TR -> 12:00 UTC
    # 17:00 TR -> 14:00 UTC
    # 19:00 TR -> 16:00 UTC
    # 21:00 TR -> 18:00 UTC
    # 23:00 TR -> 20:00 UTC
    - cron: '0 4 * * *'
    - cron: '0 7 * * *'
    - cron: '0 9 * * *'
    - cron: '0 12 * * *'
    - cron: '0 14 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch: # Elle deneme butonu

jobs:
  calistir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Kutuphaneleri Yukle
        run: pip install -r requirements.txt
      - name: Botu Calistir
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python bot.py