name: 4K AI Wallpaper Bot

on:
  schedule:
    - cron: '0 */3 * * *'    # Her 3 saatte bir (sen değiştir: */2 = 2 saatte bir, * * * * = her saat)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Botu Çalıştır
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          PIXELCUT_API_KEY: ${{ secrets.PIXELCUT_API_KEY }}
          DEEPAI_API_KEY: ${{ secrets.DEEPAI_API_KEY }}
        run: python bot.py
